### PR TITLE
Sync js-api tests from wpt.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Review by gahaas — APPROVED** [review]

**Comment by SPY** [comment]
Hi, @Ms2ger
Could you land the PR or rerun the CL if it is the reason it wasn't landed yet. I will try to resolve potential issues.

**Comment by Ms2ger** [comment]
It hasn't landed yet because I don't have the permissions to do it. Please merge if you are able.

**Comment by SPY** [comment]
Hi @rossberg 
Could you take a look?
Also, could you add me a permission for accepting PR in the repo as a champion of the proposal?

**Comment by rossberg** [comment]
Landed. I tried to add you as collaborators, but GH wants 2FA for that and I don't have my Yubikey with me. Won't be able to do that before next week. Perhaps one of the other organisation admins can help in the meantime.

**Pull request merged**
