### PR TITLE
Adding more tests for WebAssembly.Function

### PR DESCRIPTION
**Pull request by SPY**
Hi.

To close the gap in tests coverage for moving the proposal to Stage 3 tests for WebAssembly.Function were added.

### CODE REVIEW

**Comment by Ms2ger** [comment]
Not sure why these aren't in this repo, but there's also some tests at https://github.com/web-platform-tests/wpt/tree/3fcd8c9417f5b1d030f803c5415418c1b7fc5975/wasm/jsapi/function . I'll try to take another look later

**Comment by SPY** [comment]
Hi @Ms2ger. A gentle ping.

**Comment by Ms2ger** [comment]
I've imported the wpt tests in #41; could you compare your tests to see if there's any duplication?

**Comment by SPY** [comment]
Tests in #41 are almost subset of tests in this PR. I can extend tests here with missing pieces.

**Comment by SPY** [comment]
Ooops, I pushed rebase to a wrong branch. I'm going to revert it

**Pull request closed without merging**
