### PR TITLE
Merge with upstream.

### PR DESCRIPTION
**Pull request by Ms2ger**

### CODE REVIEW

**Comment by backes** [comment]
@binji What is the preferred approach here? Merge upstream or rebase on upstream?

I assume that we later need to rebase on upstream anyway (before merging into upstream), so would it be better to rebase now already?

**Comment by binji** [comment]
We generally merge on the feature branches because it's simpler to do. Rebasing now is possible, but given how often we do it (every few months to a year, it seems) the rebase will be pretty painful.

I actually didn't rebase when going back from the feature branch to upstream either, because it's still too much work. Instead, I did a final merge and then a `git reset` to the current work tree. It has the danger that some changes might be lost if you're not careful, but beats rebasing years worth of changes.

**Comment by backes** [comment]
Thanks for the explanation, Ben. LGTM then!

**Comment by Ms2ger** [comment]
Hmm, who's got push access here? @tschneidereit ? @rossberg ?

**Comment by tschneidereit** [comment]
I don't have write access, but I bet @rossberg does :)

**Pull request merged**
